import Link from 'next/link';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#0d1117] text-gray-300 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-[#161b22] p-6 sm:p-8 rounded-lg shadow-lg">
        <header className="mb-8 text-center">
          <h1 className="text-3xl sm:text-4xl font-bold text-white">Terms of Service</h1>
          <p className="text-sm text-gray-400 mt-2">Last Updated: {new Date().toLocaleDateString()}</p>
        </header>

        <article className="prose prose-invert prose-sm sm:prose-base max-w-none space-y-6">
          <p>
            Welcome to AI Baby Podcast! These Terms of Service (&quot;Terms&quot;) govern your access to and use of the AI Baby Podcast website, applications, and services (collectively, the &quot;Service&quot;). By accessing or using the Service, you agree to be bound by these Terms.
          </p>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
            <p>
              By creating an account, accessing, or using any part of the Service, you represent that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must not access or use the Service. We may modify these Terms at any time, and such modifications will be effective immediately upon posting the modified Terms on the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">2. Description of Service</h2>
            <p>
              AI Baby Podcast provides a platform for generating and listening to podcast content, potentially leveraging AI technologies for content creation and personalization (the &quot;Service&quot;). Features and offerings may evolve over time.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">3. User Accounts</h2>
            <p>
              To access certain features of the Service, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">4. User Conduct and Responsibilities</h2>
            <p>
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Violate any applicable laws or regulations.</li>
              <li>Infringe upon the rights of others, including intellectual property rights.</li>
              <li>Upload or transmit any material that is unlawful, harmful, threatening, abusive, defamatory, obscene, or otherwise objectionable.</li>
              <li>Attempt to gain unauthorized access to the Service or its related systems or networks.</li>
              <li>Interfere with or disrupt the integrity or performance of the Service.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">5. Intellectual Property</h2>
            <p>
              The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of AI Baby Podcast and its licensors. The Service is protected by copyright, trademark, and other laws. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of AI Baby Podcast.
            </p>
            <p>
              Content generated by you or for you through the Service may be subject to specific licensing terms presented at the time of creation or use.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">6. Content You Provide</h2>
            <p>
              If you submit, upload, or otherwise make available any content to the Service (&quot;User Content&quot;), you grant AI Baby Podcast a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform your User Content in connection with the Service and AI Baby Podcast&apos;s (and its successors&apos; and affiliates&apos;) business, including for promoting and redistributing part or all of the Service.
            </p>
             <p>You represent and warrant that you have all necessary rights to grant the licenses granted in this section and that your User Content does not violate any third-party rights or applicable laws.</p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">7. Termination</h2>
            <p>
              We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms. Upon termination, your right to use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">8. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. AI Baby Podcast makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">9. Limitation of Liability</h2>
            <p>
              In no event shall AI Baby Podcast or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the Service, even if AI Baby Podcast or an AI Baby Podcast authorized representative has been notified orally or in writing of the possibility of such damage.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">10. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction] (e.g., &quot;the State of California, USA&quot; or your company&apos;s operating jurisdiction), without regard to its conflict of law provisions. You should replace &quot;[Your Jurisdiction]&quot; with the actual governing jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">11. Changes to These Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl sm:text-2xl font-semibold text-white">12. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at: [Your Contact Email Address or Link to Contact Page]. You should replace this with your actual contact information.
            </p>
            <p>
                Go back to <Link href="/" className="text-purple-400 hover:text-purple-300">Homepage</Link>.
            </p>
          </section>
        </article>
      </div>
    </div>
  );
} 